[package]
name = "visits"
version = "0.3.3"
authors = [ "wasmCloud Team" ]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "visits"

[dependencies]
async-trait = "0.1"
futures = "0.3"
regex = "1.5"
once_cell = "1.8"
serde_bytes = "0.11"
serde = {version = "1.0", features = ["derive"]}
petclinic-interface = { path = "../../petclinic-interface/rust"}
wasmbus-rpc = "0.11"
wasmcloud-interface-sqldb = "0.8"
wasmcloud-interface-logging = "0.8"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
