[package]
name = "ping-interface"
version = "0.1.0"
authors = ["wasmcloud Team"]
edition = "2018"

[dependencies]
wapc-guest = "0.4.0"
serde = { version = "1.0.123" , features = ["derive"] }
serde_json = "1.0.62"
serde_bytes = "0.11.5"
rmp-serde = "0.15.4"
log = { version="0.4.14", features =["std","serde"]}
lazy_static = "1.4.0"
