[package]
name = "ui"
version = "0.3.4"
authors = [ "wasmCloud Team" ]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "ui"
path = "lib.rs"

[dependencies]
async-trait = "0.1"
futures = "0.3"
wasmbus-rpc = "0.13"
wasmcloud-interface-logging = "0.9"
petclinic-interface = { path = "../../petclinic-interface/rust"}
rust-embed = "6.3.0"
mime_guess = "2"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
