[package]
name = "todo-sql"
authors = [
  "Aayush Attri <aayush.attri@red-badger.com>",
  "Chris Whealy <chris.whealy@red-badger.com>",
  "David Laban <david.laban@red-badger.com>",
  "Stuart Harris <stuart.harris@red-badger.com>",
  "wasmcloud team",
]
edition = "2021"
version = "0.1.7"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1"
futures = "0.3"
once_cell = "1.8"
regex = "1.5"
serde = {version = "1.0", features = ["derive"]}
serde_bytes = "0.11"
serde_json = "1.0"
wasmbus-rpc = "0.13"
wasmcloud-interface-httpserver = "0.10"
wasmcloud-interface-numbergen = "0.9"
wasmcloud-interface-sqldb = "0.9"
wasmcloud-interface-logging = "0.9"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
