[package]
name = "todo"
authors = [
  "Aayush Attri <aayush.attri@red-badger.com>",
  "Chris Whealy <chris.whealy@red-badger.com>",
  "David Laban <david.laban@red-badger.com>",
  "Stuart Harris <stuart.harris@red-badger.com>",
]
edition = "2021"
version = "0.3.8"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.41"
async-trait = "0.1"
futures = "0.3"
serde = {version = "1.0", features = ["derive"]}
serde_bytes = "0.11"
serde_json = "1.0"
wasmbus-rpc = "0.13"
wasmcloud-interface-httpserver = "0.10"
wasmcloud-interface-keyvalue = "0.10"
wasmcloud-interface-logging = "0.9"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
