[package]
name = "extras"
version = "0.0.1"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wascc-actor = "0.4.0"
serde_json = "1.0"

[profile.release]
# Optimize for small code size
opt-level = "s"
