name: KVCOUNTER

on:
  push:
    branches: [ main ]
    paths:
    - "actor/kvcounter/**"
  pull_request:
    branches: [ main ]
    paths:
    - "actor/kvcounter/**"

env:
  CARGO_TERM_COLOR: always
  working-directory: ./actor/kvcounter

jobs:
  cargo_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add wasm32-unknown-unknown
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --verbose
      working-directory: ${{ env.working-directory }}
    - name: Check fmt
      run: cargo fmt -- --check
      working-directory: ${{ env.working-directory }}

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - name: Add wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown
      - name: Run cargo clippy
        run: cargo clippy --all-features
        working-directory: ${{ env.working-directory }}
